FROM python:3.10

EXPOSE 5000/tcp

COPY requirements-ordenes.txt ./
RUN pip install --upgrade --no-cache-dir pip setuptools wheel
RUN pip install --no-cache-dir wheel
RUN pip install --no-cache-dir -r requirements-ordenes.txt

COPY . .

WORKDIR "/src"

CMD [ "uvicorn", "ordenes.main:app", "--host", "localhost", "--port", "8000", "--reload"]
